config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "blog_posts#index"
  resources :blog_posts do
    resource :cover_image, only: [:destroy], module: :blog_posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_one_attached :cover_image
  has_rich_text :content

  validates :title, presence: true
  validates :content, presence: true, length: {minimum: 10}

  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at.present? && published_at <= Time.current
  end

  def scheduled?
    published_at.present? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
    :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :authenticate_user!

  def destroy
    @blog_post = BlogPost.find(params[:blog_post_id])
    @blog_post.cover_image.purge

    respond_to do |format|
      format.html { redirect_to edit_blog_post_path(@blog_post), notice: "Cover image removed!" }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@blog_post, :cover_image)) }
    end
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_post, only: [:show, :update, :edit, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @blog_posts = if user_signed_in?
      BlogPost.all.sorted
    else
      BlogPost.published.sorted
    end
    @pagy, @blog_posts = pagy(@blog_posts, items: 10)
  rescue Pagy::OverflowError
    redirect_to root_path(page: 1)
    # params[:page] = 1
    # retry
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
    # This is to pre-populate the published_at field with the current time so you can hit 'Create' without having to change the date
    @blog_post.published_at = Time.current
  end

  def create
    @blog_post = BlogPost.create(blog_params)
    if @blog_post.save
      redirect_to @blog_post, notice: "Post created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_params)
      redirect_to @blog_post, notice: "Post updated!"
    else

      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to blog_posts_url, notice: "Post deleted!"
  end

  private

  def blog_params
    params.require(:blog_post).permit(:title, :cover_image, :content, :published_at)
  end

  def set_post
    @blog_post = BlogPost.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def body_class
    controller_name.dasherize
  end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
  def output_time_info(blog_post)
    if blog_post.scheduled?
      content_tag(:p, "To be published on #{blog_post.published_at.to_fs(:long)}")
    elsif blog_post.published?
      content_tag(:p, "#{time_ago_in_words(blog_post.published_at)} ago")
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 800, 600 ]) %>
  <% end %>

  <figcaption class="attachment__caption text-left">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 max-w-4xl mx-auto") do |form| %>

  <% if form.object.errors.any? %>
    <%= render "shared/errors", object: blog_post %>
  <% end %>

  <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-6">
      <%= form.label :cover_image, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.file_field :cover_image, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      <% if blog_post.cover_image.present? %>
        <div id="<%= dom_id(blog_post, :cover_image)%>">
          <%= image_tag blog_post.cover_image, class: "w-1/3" %>
          <%= link_to "Remove cover image", blog_post_cover_image_path(blog_post), data: { turbo_method: :delete, turbo_confirm: "Delete cover image?"} %>
        </div>
      <% end %>
  </div>

  <div class="mb-6">
    <%= form.label :content, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.rich_text_area :content, class: "min-h-[10rem] md:min-h-[15rem] h-auto shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-6">
    <%= form.label :published_at, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.datetime_select :published_at, include_blank: true,  class: "h-40 shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>


  <div class="flex items-center justify-center">
    <%= form.submit "Submit", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded cursor-pointer focus:outline-none focus:shadow-outline" %>
  </div>

<% end %>

app/views/blog_posts/edit.html.erb
<%= render "form", blog_post: @blog_post %>

app/views/blog_posts/index.html.erb
<h1>Ann's Blog</h1>

<% @blog_posts.each do |blog| %>

  <h2><%= link_to blog.title, blog %>
  <% if blog.draft? %>
    <span class="py-2 px-3 ml-4 rounded text-base bg-gray-100 text-gray-900 font-normal">Draft</span>

  <% elsif blog.scheduled? %>
      <span class="py-2 px-3 ml-4 rounded text-base bg-orange-200 text-gray-900 font-normal">Scheduled</span>
  <% end %>
  </h2>
  <% if blog.cover_image.present? %>
    <figure class="h-auto w-11/12 max-w-sm mx-auto">
      <%= image_tag blog.cover_image %>
    </figure>
  <% end %>
  <p><%= blog.content %></p>
  <%= output_time_info(blog) %>
<% end %>

<% if @pagy.count > @pagy.items %>
  <footer class="my-14 flex justify-center">
    <%# Using double equal which will not sanitize html - but we trust the Pagy gem %>
    <%== pagy_nav(@pagy)%>
  </footer>
<% end %>

app/views/blog_posts/new.html.erb
<%= render "form", blog_post: @blog_post %>

app/views/blog_posts/show.html.erb
<h2><%= @blog_post.title %></h2>
<% if @blog_post.cover_image.present? %>
  <%= image_tag @blog_post.cover_image %>
<% end %>
<p><%= @blog_post.content %></p>
<%= output_time_info(@blog_post) %>

<section class="actions sm:flex sm:gap-3">
<%= link_to "Back to All Posts", blog_posts_path, class:"inline-block bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 my-2 rounded" %>

<% if user_signed_in? %>
  <%= link_to "Edit", edit_blog_post_path(@blog_post), class:"inline-block bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 my-2 rounded" %>
  <%= button_to "Delete", @blog_post, method: :delete, data: { turbo_confirm: "You sure??" }, class:"inline-block bg-gray-800 my-2 hover:bg-gray-900 text-white font-bold py-2 px-4 rounded" %>
<% end %>

</section>

app/views/layouts/_header.html.erb
<header class="bg-gray-800 py-4 mb-8 ">
  <nav class="sm:flex sm:gap-3 justify-between items-center max-w-6xl w-11/12 mx-auto">
    <div>
      <%= link_to "Blog Posts", blog_posts_path, class: "text-white text-lg font-bold px-4 py-2" %>
    </div>
    <div class="flex gap-3">
      <% if user_signed_in? %>
        <%= link_to 'New Blog Post', new_blog_post_path, class: "text-white hover:text-gray-300 px-4 py-2 rounded" %>
        <%= button_to "Log Out", destroy_user_session_path, method: :delete, data: { turbo_confirm: "Are you sure you want to log out?" }, class: "text-white hover:text-gray-300 px-4 py-2 rounded" %>
      <% else %>
        <%#= link_to "Log In", new_user_session_path, class: "text-white hover:text-gray-300 px-4 py-2 rounded" %> 
        <%#= link_to "Sign Up", new_user_registration_path, class: "text-white hover:text-gray-300 px-4 py-2 rounded %>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body <%= body_class %>>
    <%= render "layouts/header" %>

    <main class="content prose mx-auto w-11/12 max-w-6xl">
      <% flash.each do |type, message| %>
        <%= content_tag(:div, message, class: "flash #{type}") %>
      <% end %>
  
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_errors.html.erb
 <% if object.errors.any? %>
    <section class="errors">
      <h2>Oops! Your form could not be saved.</h2>
      <h3>Please correct the following <%= pluralize(object.errors.size, "error") %></h3>

        <ul>
          <% object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </section>
  <% end %>